### ISSUE TITLE
Accept all licenses

### ISSUE THREAD

**Issue by rkistner** [embarkmobile/android-sdk-installer#5]
The current `echo y | android update sdk ...` approach only accepts the first license. This has the nice side-effect of preventing the install of the MIPS and Intel emulator images, but is not a very stable solution, and may break in the future. It also prevents the user from installing e.g. the Intel emulator image if he really wants to.

The following alternative has been suggested by @sebv, which accepts all the licenses:

```
( while [ 1 ]; do sleep 5; echo y; done ) | android update sdk ...
```

The problem currently is that it causes all emulator images to be installed with e.g. `sysimg-17`, which significantly increases the installation time.

To implement this, we therefore first need a way to filter out the emulator images that are installed.

**Comment by gVien** [comment]
I know this is closed but I have a question related to the way Android is installed. As @gildegoma mentioned that updating the SDK with `android update sdk ...` would install the packages inside either `build-tools`, `platforms`, `extras`,  `samples`, and `system-images` directories inside $ANDROID_HOME, but does it update any other configuration files inside the `tools` directory or other directories? 

I'm automating the installation of Android SDK with Puppet but plan to package all the `platforms/android-XX` directories after updating the SDK into RPM format and then combine them with other Android packages (extras, system-images, etc) during the installation. However, I wasn't sure if doing this would break anything, considering I'm not so sure if updating the SDK would update any configuration files inside $ANDROID_HOME.

```
 55M  build-tools/
146M  platforms/android-10
 82M  platforms/android-15
...
210M  system-images/android-17/default/armeabi-v7a
281M  system-images/android-17/default/x86
...
 13M  extras/android/m2repository
 12M  extras/android/support
...
----
4.2G  in total
```
